# Generated by Django 5.1.2 on 2024-10-13 09:23

import banking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(default='1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='banking.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=banking.models.generate_account_number, max_length=10, unique=True),
        ),
    ]
