# Generated by Django 5.1.2 on 2024-10-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
